version: '3.9'

x-typeorm: &typeorm-env
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  JWT_SECRET: ${JWT_SECRET}

volumes:
  reaccoon_postgres_data: {}

networks:
  reaccoon-network:
    name: reaccoon-network
    driver: bridge

services:

  reaccoon-postgres-db:
    image: postgres:14
    container_name: ${POSTGRES_HOST}
    environment:
      <<: *typeorm-env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: on-failure
    stdin_open: true
    tty: true
    networks:
      - reaccoon-network
    volumes:
      - reaccoon_postgres_data:/var/lib/postgresql@14/data

  reaccoon:
    profiles:
      - reaccoon
      - all
    container_name: reaccoon
    build:
      dockerfile: development/Dockerfile
      context: ../
    networks:
      - reaccoon-network
    volumes:
      - ../src:/home/node/reaccoon/src
    depends_on:
      - reaccoon-postgres-db
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      <<: *typeorm-env
    entrypoint: [ "npm", "run", "start:dev", "--tsc" ]